#!/bin/bash

npm i -D glebmachine/node-pac
echo '
if [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ];
  then
    echo "Sorry, you work on windows, no hooks for you";
  else
    echo "Make sure all modules are packed";
    pac
    git add .modules
fi
' > .githooks/pre-commit/pac
chmod +x .githooks/pre-commit/pac
